### ISSUE TITLE
Component not found unless the app/Livewire folder is written with a capital L

### ISSUE THREAD

**Issue by fgschafer** [rainlab/livewire-plugin#1]
I noticed that the component isn’t found unless the app/Livewire folder is written with a capital L, instead of lowercase as it is written in the first mention of the readme file.

**Comment by daftspunk** [comment]
This can be caused by using older versions of October CMS. The latest version includes a class loader that allows lower case folder names.

The readme has been updated to include a captial L (fe5b1edb0af6fe544ec77f6be05fd6be4b042f59)

Thanks

**Comment by fgschafer** [comment]
@daftspunk the system build was the latest one at this moment.  OC 3.3.6

**Comment by daftspunk** [comment]
> the system build was the latest one at this moment. OC 3.3.6

Thanks for reporting back. I couldn't reproduce it using this version, using the [docker dev image](https://octobercms.com/docker-dev-image).

**Comment by fgschafer** [comment]
Thank you for your answer and for this great plugin.  FYI, I was using OC installed via composer on a LEMP stack, on Ubuntu 22.04
