### ISSUE TITLE
Livewire 3 Issues

### ISSUE THREAD

**Issue by kOld** [rainlab/livewire-plugin#3]
Tried to use Livewire 3 with this plugin but I've found a couple of issues:

- Styles and Scripts needs to be compiled with a new class
- Livewire::mount method now returns the compiled string, calling ->html() causes a error
- I can only use .blade.php views, twig / .htm does't work anymore (I didn't manage to solve this)

If it helps I can make a pull request for the first two items, the way I maintained compatibility with v2 is checking if the old classes still exists, like this:

### LivewireHelper.php
```php
    public static function renderStyles($options = [])
    {
        if (method_exists('\Livewire\LivewireManager', 'styles')) {
            return Livewire::styles($options);
        }
        return \Livewire\Mechanisms\FrontendAssets\FrontendAssets::styles($options);
    }
```
```php
    public static function renderScripts($options = [])
    {
        $turboScript = Url::asset('plugins/rainlab/livewire/assets/js/livewire-turbo.js');

        if (method_exists('\Livewire\LivewireManager', 'scripts')) {
            if (!isset($options['asset_url'])) {
                $options['asset_url'] = Url::asset('');
            }

            $scriptStr = Livewire::scripts($options);
        } else {
            $scriptStr = \Livewire\Mechanisms\FrontendAssets\FrontendAssets::scripts($options);
        }

        $scriptStr = str_replace('data-turbolinks-eval="false"', '', $scriptStr);

        $scriptStr .= "<script> addEventListener('page:loaded', function() { if (window.oc && oc.useTurbo && oc.useTurbo() && !window.Livewire) window.location.reload(); }, { once: true }); </script>";

        $scriptStr .= '<script src="' . $turboScript . '" data-turbo-eval="false"></script>';

        return $scriptStr;
    }
```

### Plugin.php - register()
```php
        if (method_exists('\Livewire\LivewireManager', 'setScriptRoute')) {
            Livewire::setScriptRoute(function ($handle) {
                return Route::get(Url::asset('/livewire/livewire.js'), $handle);
            });
        }
```

### LivewireNode.php - compile()
```php
        if (class_exists('\Livewire\LifecycleManager')) {
            $compiler
                ->write(")->html();\n");
        } else {
            $compiler
                ->write(");\n");
        }
```

**Comment by daftspunk** [comment]
Thanks for this, go for a pull request and then we'll see what we can do about the htm view files.

**Comment by daftspunk** [comment]
Regarding the loss of `.htm` support, this commit is the reason: https://github.com/livewire/livewire/commit/c9693ea7d0930c22e52cdf53fd963f7cea5729b0

Instead of using `View::make()` it was swapped for `View::file()` which makes support for blade files exclusive and drops support for `.php` view files, in addition to `.htm` files registered by October CMS.

You could ask them to consider restoring the option to use PHP as a template syntax for Livewire, otherwise, we will need to drop it also.

**Comment by daftspunk** [comment]
Here is a modified method we could propose (admittedly untested). It would let us at least nullify `livewire.view_path` to revert to the base view renderer and restore support for PHP and Twig and keep the fun going.

```php
protected function getView($component)
{
    if (method_exists($component, 'render')) {
        $viewOrString = wrap($component)->render();
    } elseif ($viewPath = config('livewire.view_path', resource_path('views/livewire'))) {
        $dotName = $component->getName();

        $fileName = str($dotName)->replace('.', '/')->__toString();

        $viewOrString = View::file($viewPath . '/' . $fileName . '.blade.php');
    } else {
        $viewOrString = View::make("livewire.{$component->getName()}");
    }

    $properties = Utils::getPublicPropertiesDefinedOnSubclass($component);

    $view = Utils::generateBladeView($viewOrString, $properties);

    return [ $view, $properties ];
}
```

**Comment by daftspunk** [comment]
If this idea is not accepted, a workaround is in place here: eeba8d68a35b3ea821abf03323593b93b9e153c5

**Comment by kOld** [comment]
Just tested the workaround with the small demo using app/views/livewire/counter.htm and works as expected, the issue probably can be closed.

Thanks for solving this so fast
